# Environment variables loaded automatically from docker/.env
# Simple usage: cd docker && docker-compose --profile dev up

services:
  # AI Agent Service - Development Mode
  ai-agent-service-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    container_name: ${DEV_CONTAINER_NAME:-ai-agent-service-dev}
    ports:
      - "${PORT:-8000}:${CONTAINER_PORT:-8000}"